name: Continuous Integration
on: pull_request
jobs:
  run_code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run linting
        run: |
          go fmt ./...
          go vet ./...
      - name: Run tests
        run: go test -covermode=count -coverprofile=coverage.out ./... 
      - name: Check code coverage > 50%
        run: |
          total=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
          if (( $(echo "$total <= 50" | bc -l) )) ; then
            echo "code coverage $total% < 50%"
            exit 1
          fi
